- img: 14-min.png
  figcaption: "Cloning Facility - April"

- img: 15-min.png
  figcaption: "Cold Frame Greenhouses - June"

- img: 16-min.png
  figcaption: "Flat Roof Retractable Greenhouse - June"

- img: 2-min.png
  figcaption: "Flat Roof Retractable Greenhouse - June"

- img: 1-min.png
  figcaption: "Aerial Photo - Flat Roof Retractable Greenhouse"

- img: 8-min.png
  figcaption: "Cold Frame Greenhouses - August"

- img: 13-min.jpg
  figcaption: "Flat Roof Retractable Greenhouse - September"

- img: 11-min.jpg
  figcaption: "Flat Roof Retractable Greenhouse - Mid September"

- img: 12-min.jpg
  figcaption: "Flat Roof Retractable Greenhouse - October"

- img: 6-min.jpg
  figcaption: "Cold Frame Greenhouse - October"

- img: 9-min.jpg
  figcaption: "Cold Frame Greenhouses - October"

- img: 7-min.jpg
  figcaption: "Cold Frame Greenhouse - October"

- img: 3-min.png
  figcaption: "Flat Roof Retractable Greenhouse - Mid October"

- img: 4-min.png
  figcaption: "Harvest - Cold Frame Greenhouses"

- img: 5-min.png
  figcaption: "Harvest - Flat Roof Retractable Greenhouses"